---
title: "Presentation"
author: "Lucas"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
# load packages -------------------------------------------------------------------------------

library(data.table)
library(dtplyr)
library(tidyverse)
library(ranger)
library(caret)
```

```{r data, include=FALSE}
# read data -----------------------------------------------------------------------------------

# data <- fread("./data/clean/sample_bavaria.csv", sep = ",", header = TRUE)
data <- fread("../data/clean/sample_206934.csv", sep = ",", header = TRUE)

data$CType <- dplyr::recode(data$CType, 
                            `70` = 20L,
                            `80` = 21L)

data$State <- as.factor(data$State)
data$X <- as.numeric(data$X)
data$Y <- as.numeric(data$Y)
data$Year <- as.factor(data$Year)
data$CType <- as.factor(data$CType)
data$PCType <- as.factor(data$PCType)
data$PPCType <- as.factor(data$PPCType)
data$SType <- as.factor(data$SType)
data$SElev <- as.numeric(data$SElev)

data <- data %>% drop_na()
```

```{r split, include=FALSE}
# split data ----------------------------------------------------------------------------------

split_data <- function(dataset) {
  dataset <- dataset %>% select(-OBJECTID) %>% as.data.table()
  years <- unique(dataset$Year)
  tail <- years[(length(years)-2):(length(years)-1)]
  head <- years[1:(length(years)-2)]
  rest <- years[length(years)]
  
  train <- dataset %>% 
    filter(Year %in% head) %>% 
    as.data.table()
  
  test <- dataset %>% 
    filter(Year %in% tail) %>% 
    as.data.table()
  
  eval <- dataset %>% 
    filter(Year %in% rest) %>% 
    as.data.table()
  
  return(list(train,test,eval))
}

split <- split_data(data)
train_data <- split[[1]]
test_data <- split[[2]]
eval_data <- split[[3]]

# clean workplace -----------------------------------------------------------------------------

rm(data, split)
gc()
```


```{r model, include=FALSE}
# model ---------------------------------------------------------------------------------------

res <- ranger(CType ~ ., data = train_data,
              importance="impurity",
              oob.error = TRUE,
              seed = 187,
              probability = FALSE,
              num.trees=100
)

pred <- predict(res, data = test_data)

gc()
```

```{r eval, echo=FALSE}
cmat <- confusionMatrix(pred$predictions ,test_data$CType)
cmat$table %>% confusionMatrix()

plot(res$predictions, las = 2)

imp <- res$variable.importance
barplot(imp[order(imp, decreasing = TRUE)], las = 2)
```

```{r eval acc, echo=FALSE}
# accuracy for each class

acc_c <- data.frame(pred$predictions, test_data$CType) %>% 
  group_by(pred.predictions) %>% 
  summarize(acc = mean(pred.predictions == test_data.CType)) %>% 
  arrange(acc)

ggplot(data=acc_c, aes(x=pred.predictions, y=acc)) +
  geom_bar(stat="identity")

table(test_data$CType)[-22]

acc_c <- acc_c %>% arrange(pred.predictions)

je <- data.frame(table(test_data$CType)[-22], 
                 acc_c$acc )

ggplot(data = je, aes(x=acc_c.acc, y=Freq)) +
  geom_point(position = "jitter")
```